### ISSUE TITLE
extracting error

### ISSUE THREAD

**Issue by xland** [elegantweb/nwjs-vue#11]
Mac Os:

> Fetching NW.js binary... { platform: 'darwin',
>   arch: 'x64',
>   version: '0.32.4',
>   flavor: 'sdk' }
> 
> Error: ERROR_EXTRACTING path = /project/cnblogs/jna/node_modules/nwjs-builder-phoenix/caches/nwjs-sdk-v0.32.4-osx-x64.zip
>     at /project/cnblogs/jna/node_modules/nwjs-builder-phoenix/src/lib/util/archive.ts:25:15
>     at step (/project/cnblogs/jna/node_modules/nwjs-builder-phoenix/dist/lib/util/archive.js:32:23)
>     at Object.next (/project/cnblogs/jna/node_modules/nwjs-builder-phoenix/dist/lib/util/archive.js:13:53)
>     at fulfilled (/project/cnblogs/jna/node_modules/nwjs-builder-phoenix/dist/lib/util/archive.js:4:58)
>     at <anonymous>

**Comment by xland** [comment]
nwjs-builder-phoenix doesn't support MacOs????!!!

**Comment by ghost** [comment]
I think this issue is not related to the boilerplate, please report it on nwjs-builder-phoenix, thank you.
