### ISSUE TITLE
Communication between bg.js and main windoe

### ISSUE THREAD

**Issue by anoopmb** [elegantweb/nwjs-vue#14]
hi thanks for your boiler plate,

Can you explain how to communicate between background script and main window 

means to run some functions in node process

**Comment by ghost** [comment]
[Google](https://www.google.com/search?q=chrome+extension+communicate+with+background+script&oq=chrome+extension+commu&aqs=chrome.4.69i57j0l5.8849j0j0&sourceid=chrome&ie=UTF-8)
