### ISSUE TITLE
unable to package files in directory.

### ISSUE THREAD

**Issue by Sombian** [elegantweb/nwjs-vue#15]
im trying to package some files with .exe, .dll. sys extension under background folder.
it works on dev, but on product i got ENOENT

**Comment by ghost** [comment]
If you are installing them as npm package, make sure they are in `dependencies` not `devDependencies`.

**Comment by Sombian** [comment]
> If you are installing them as npm package, make sure they are in `dependencies` not `devDependencies`.

guess i need to clear my words,
im trying to bundle [goodbyedpi](https://github.com/ValdikSS/GoodbyeDPI) on my app.
thing is goodbyedpi dont even extracted out when build.

**Comment by ghost** [comment]
only packages inside `dependencies` will be extracted, packages inside `devDependencies` won't.

**Comment by Sombian** [comment]
I solved this by declear regex filter in background webpack and import files although it doesnt need to, since only imported files will be extracted. Thank you for your quick response. May close this now.
