### ISSUE TITLE
webpack problem with node modules

### ISSUE THREAD

**Issue by FxIII** [elegantweb/nwjs-vue#3]
I am not able to require native module like "usb".
I try to import right under the <script> tag 

usb = require("usb");

**Comment by FxIII** [comment]
Resolved by adding the relevant dependencies in <projectDir>/app/package.json (not only under <projectDir>/package.json)

**Comment by ghost** [comment]
@FxIII if your packages contain something native, you always should add it to /app/package.json, thank you.
