### ISSUE TITLE
Update for the latest versions of the npm packages

### ISSUE THREAD

**Issue by mehmetkursataydin** [elegantweb/nwjs-vue#7]
![capture](https://user-images.githubusercontent.com/36981992/43775035-e4b1f406-9a53-11e8-975a-af78e25a1502.PNG)

Can we get an update to this template, because these versions have some breaking changes and npm run dev won't work.

**Comment by ghost** [comment]
I don't think that Webpack@4 is good idea,
Most packages are not compatible with it yet.
